export const ActionTypes={
    SET_DOGS: "SET_DOGS",
    SET_TEMPERAMENTS:"SET_TEMPERAMENTS",
    SET_FILTER_TEMPERAMENTS:"SET_FILTER_TEMPERAMENTS",
    SET_BREED: "SET_BREED",
    ORDER_BY_NAME: "ORDER_BY_NAME",
    ORDER_BY_WEIGHT : "ORDER_BY_WEIGHT",
    SELECTED_DOG:"SELECTED_DOG",
    POST_DOG:"POST_DOG",
    FILTER_CREATED:"FILTER_CREATED"
}